### ISSUE TITLE
Unsupported device: iPad Air 1 (J72AP) / iOS 9.0.2 (13A452)

### ISSUE THREAD

**Issue by TwentyFour-24** [Siguza/cl0ver#30]
Hello Siguza,

first of all, great work and thank you for putting this up.
Hereby the demanded files for my iPad Air (Cellular), iOS 9.0.2, generated with the pre-compiled 1.0.5

Output:
http://pastebin.com/A6ZqkaZY

Panic Log
http://pastebin.com/D6PnQjCj

If you need further information, just let me know.

Best regards

**Comment by Siguza** [comment]
The panic value is below the kernel text base (the value `0xffffff800480abb0` should be above `0xffffff801a404000`)... idk, this must be an iPad thing. :/
I can only suggest what I suggested to others: go into airplane mode, and kill all apps before trying it.

**Comment by TwentyFour-24** [comment]
Okey on it...

So just to be clear:
"panicString" : "panic(cpu 0 caller **0xffffff801a4fd510**): \"Kernel instruction fetch abort: pc=`0xffffff800480abb0 `iss=0xf far=`0xffffff800480abb0`. 

So the `"code"` values have to be greater than the **"bold"** value? 
Cause in the usage guide you say, you need values of 0xffffff80 and not 0xffffff81... is that criteria still applying as well?

**Comment by Siguza** [comment]
Nope, the value you have to be higher than is further down:

"panicString" : "panic(cpu 0 caller 0xffffff801a4fd510): \"Kernel instruction fetch abort: pc=**0xffffff800480abb0** iss=0xf far=0xffffff800480abb0. Note: the faulting frame may be missing in the backtrace.\"\nDebugger message: panic\nOS version: 13A452\nKernel version: Darwin Kernel Version 15.0.0: Thu Aug 20 13:11:14 PDT 2015; root:xnu-3248.1.3~1\/RELEASE_ARM64_S5L8960X\niBoot version: iBoot-2817.1.94\nsecure boot?: YES\nPaniclog version: 5\nKernel slide:     0x0000000016400000\nKernel text base: `0xffffff801a404000`

And yes, you need to be below `0xffffff81...`, because the kernel text base will always be low enough so that all values above 0xffffff81 are out of range (well, on iOS 9 at least).

**Comment by TwentyFour-24** [comment]
How about those... if I didn't screw up, cause it's in the middle of the night here. 😆

Output:
http://pastebin.com/c35QE6Be

Panic Log:
http://pastebin.com/GGjurczf

**Comment by HiddenUnkn0wn** [comment]
I'm curious cause I have a iPad Air 1 (cell) on iOS 9.0.2 what do u mean by lock screen activated. And also can you dumb down the criteria that Siguza posted so I can understand it?

**Comment by TwentyFour-24** [comment]
I was just trying around, sometimes I issued the commend via SSH, sometimes in MobileTerminal. In that last try, I SSH'ed into the iPad, closed all apps, and then just hit the on/off button, so the screen turns black.
Didn't get that tiny short bluescreen, which I normally got when device's screen was active.

To sum up Siguza's criteria:
- both values at `Kernel instruction fetch abort:`(KIFA) and `Kernel text base:` (KTB) should be something like **0xffffff80...** and not 0xffffff81...
- **KIFA** value has to be greater than **KTB** value (e.g. 0xffffff**8021**2f7168 >0xffffff**8020**e04000)

But let's wait for Siguza's response whether my file is helpful at all.

**Comment by Siguza** [comment]
Yes, that last one finally looks like a success! :D  
Here are your config values:

    0xffffff800453e000
    0xffffff80044f7168

(@HiddenUnkn0wn: It's very likely that these values will work for you as well.)

Annoyingly enough, they're the same as for a lot of other devices on 9.0.2. The next step would be to run `./cl0ver dump`, but you might wanna try the `offset.dat` files of some other devices first. The anchor and vtable match those of all these models:

- N51AP/N53AP
- N66AP/N71AP
- N66mAP/N71mAP

(That's 3 files you'd need to try and run `./cl0ver` (no "dump") with.) If the offsets happen to be the same too, you can save yourself a lot of time. If not, you're gonna get a panic.

**Comment by TwentyFour-24** [comment]
No successful kernel dump so far, tried like 20-30 times during yesterday's evening movie. Sometimes the blue crash screen came instantly, sometimes it really filled up half of the screen with "dumping lines" before crashing eventually.

Testing that new build from #34 now.

**Comment by Siguza** [comment]
With config values that are only the slightest bit off, it wouldn't be possible to even get to the point where `__TEXT` & co. are enumerated, the device would always crash before that.  
And yes, I imagine safe mode would reduce the general activity of the device, which should help. Other than that I can only suggest to keep trying.

As for a "visible difference" with the experimental build: The first thing that gets dumped are the `__TEXT` and `__DATA` segments, and that will look exactly the same for both stable and experimental. The difference is that once that's through, the stable build is only about 20% done, whereas the experimental build should be at ca. 95%.

In case you care about the internals:  
The problem with dumping is that is has to be done in chunks of 4096 bytes. Due to the nature of the vulnerability used, every chunk dumped has a tiny chance of not working out, which usually manifests in a panic.  
Let's say the chance of it *not* crashing were 99.9%.  
For a full kernel of 30MB, that's 7680 chunks, so the chance of success is 99.9%<sup>7680</sup> = 0.046%, or a 1 in 2173 chance of getting through.
With the experimental build, a mere 6 MB get dumped, i.e. 1536 chunks, yielding a success rate of 99.9%<sup>1536</sup> = 21.5%.  
Now, the chance of success seems to depend on device specs and configuration anyway, so that will of course vary from case to case, but there should nevertheless be an exponential increase in the chance of success.

**Comment by TwentyFour-24** [comment]
Okey thanks for clarifying this. So based on the following video, how close are we? :D
That's one of the longest runs, before a panic, soemtimes it does a lot earlier.

https://youtu.be/oDCiVN4tDuo

**Comment by Siguza** [comment]
About 40%.

**Comment by TwentyFour-24** [comment]
Wow....

I don't know how I get there, but here is it... my full kernel dump! <3
http://pastebin.com/5AMefaEH

Well you don't need that log anyways, so here are my offsets attached, patching went fine and kmap runs smoothly. I guess we can close this hereby. 😄

[offsets.dat.zip](https://github.com/Siguza/cl0ver/files/771633/offsets.dat.zip)

**Comment by TwentyFour-24** [comment]
I just went back in my mind, to gather what I did to get this huge step with like one try (for others struggling as well).

- this time i was using Terminal on my Mac, not MobileTerminal directly on the iPad
- so no airplane mode, issued the commands over SSH
- safe mode (Volume Up button)
- cleared all background apps and opened the Terminal app on iPad though
- waited like one minute

now comes the weird part... I opened iTunes to download updates for all apps into my library.

- so i guess I just had iTunes running in the background

Then I just did `./cl0ver dump` and it ran smoothly through.

**Comment by Siguza** [comment]
Nice, that's the second on within the hour! :D 

8e0a7bba8ac1a21bf087dc459cb9a388680f6c19 Merged.

**Comment by TwentyFour-24** [comment]
Again thank you for your great work! You helped me a lot, and I guess many other people as well, really good job!

My only tragedy is that I only saved the 10.2 "update" blob file and not the "erase" one, so I guess I'm still stuck on 9.0.2 :D

**Comment by Siguza** [comment]
"Update blob"? Since when is that a thing? o.0

**Comment by TwentyFour-24** [comment]
For futurerestore it seemingly is one...
https://github.com/tihmstar/futurerestore/issues/57

Used Ticketbox to save the blobs, exported the "update" one, then tried to export the "erase" one, told me same size and same name, so I thought it doesnt matter.
Too bad 1Conans one's were screwed cuz I didnt update the right board value. In both cases I felt safe, due to having "valid" blobs :D

**Comment by Siguza** [comment]
Well there's something I didn't know... that's sad for you, but I guess at least you're prepared for the next time, whenever that may come... :/

**Comment by TwentyFour-24** [comment]
And normally Ticketbox saves all blobs automatically, but not in my case, since it tried to save them to ~/.shsh folder. Too bad that folder was already existing - from I don't know, maybe tinyumbrella, at least some ios 6 shsh file - and screwing up ticketbox, which of course didn't tell me that.

Yep indeed, rather slapstick, but I got my lesson, let's see what comes.

**Comment by prodigymd** [comment]
Did ticket box not retrieve the shsh2 files for both erase and update? It did for me....update to the new ticketbox, request SHSH2 again (I know 10.2 is not being signed) BUT the new update fixes the generator issue not matching the blob. Also, since you only exported the update one, but they are still there, even if you didn't export them. So go get them again and try it out

**Comment by TwentyFour-24** [comment]
It did, but it did not save them, so they were gone after I closed the program. I found out too late, that this was caused by that freaking .shsh folder already being there from year 2013 or sth.
Ticketbox didn't write anything to that folder, but neither told me sth is wrong with the permissions

So I could only fix the wrong generator values from my both files saved in other locations by re-importing them. But thats unfortunately just those with "Update" tag.

**Comment by leetut** [comment]
I'm having the issue of not getting the correct generator, it's in nvram -p as mine but future restore never finds it, always same number generated first, saved 10.2 blobs via conan, the latest working ones, iPad Air 9.0.2 any ideas?

**Comment by TwentyFour-24** [comment]
Had a similar problem, but my blob file was saved with ticketbox. The was a wrong generator value, which led to the same problem you described.

The generator value generates the ApNonce, which should match the one from your blob file, so futurerestore can instantly go restore with the right nonce. I this case, the ApNonce generated is not the one the blob is expecting.

We could help you better or atleast exclude, that your blob file is currupted, if you provide the output log of futurerestore and the blob file or its output of the validation from https://tsssaver.1conan.com/check.php.

**Comment by leetut** [comment]
I have to run cl0ver first or nonceEnabler won't work, also the "nvram com.apple.system" command only works with a lower case "s" all the guides I found show a capital S, don't know if that even matters as I'm a noob, any insight is appreciated
blob:
http://pastebin.com/ut7EQZ4H

cl0ver:
http://pastebin.com/Hx1zHALX

nonceEnabler:
http://pastebin.com/dJFzyZMq
http://pastebin.com/T2GqhY9L

futurerestore:
http://pastebin.com/MCV9FN2U

**Comment by Siguza** [comment]
Yes, the "S" has to in uppercase, otherwise you're setting a variable no-one is checking. If you can't set it, even as root, that meansnonceEnabler fails.
I recently added an `nvpatch` command to [kern-utils](https://github.com/Siguza/ios-kern-utils/releases), which you should be able to use in nonceEnabler's place like so:

    nvpatch com.apple.System.boot-nonce

After that, setting the variable with the `nvram` command should be possible as root.

**Comment by leetut** [comment]
I installed the deb
nvpatch com.apple.System.boot-nonce=0xf3f8421ce0ff416e
managed to run that on iPad terminal, got a blue screen and reboot
made no difference to my usual restore errors

can't seem to run it on Mac terminal I've probably missed something
http://pastebin.com/nkZjmRSN

and this is same as before with lowercase s
nvram -p
backlight-level	1617
com.apple.system.boot-nonce	0xf3f8421ce0ff416e
boot-args	
obliteration	handle_message: Obliteration Complete
auto-boot	true
oblit-begins	OblitType: ObliterateDataPartition. No reason given.
Leetut:~ root#

**Comment by Siguza** [comment]
Why does everyone keep mis-using nvpatch? -.-  
Run the **exact** line from my last comment, with no `=` and nothing.  
And then **after that** you run:

    nvram com.apple.System.boot-nonce=0xf3f8421ce0ff416e

**Comment by leetut** [comment]
Lol sorry, worked and restored first time thank you!

**Comment by Siguza** [comment]
Glad to hear that. :)  
I guess I should catch such usage in `nvpatch`...

**Comment by ubiko** [comment]
@Siguza I get `[!] Failed to get kernel task ((os/kern) failure, kernel_task = 0)` trying tu use nvpatch, any idea?

**Comment by leetut** [comment]
Think I got past that by running cl0ver first

**Comment by Siguza** [comment]
@leetut cl0ver wasn't made for anything below iOS 9.

@ubiko Do you have the latest untether installed? (Version 2.3 of the "TaiG 8.1.3-8.x Untether" package in Cydia.)

**Comment by leetut** [comment]
Pretty sure couldn't get past that warning unless I used clover first on my 6+ taig 8.4, I haven't updated this device yet, just set the generator for later

**Comment by Siguza** [comment]
@leetut Pretty sure you wouldn't get far on 8.4, you'd run into some "Unrecognized OS version" quite early on.

**Comment by brymonster** [comment]
Getting BSOD reboot when running `nvpatch com.apple.System.boot-nonce` after cl0ver. ideas?

**Comment by Siguza** [comment]
It seems the issues that are plaguing iOS 10 are already present on iOS 9 for iPad Air models. Other people reported success with an experimental build from the iOS 10 branch that I posted in [this comment](https://github.com/Siguza/ios-kern-utils/issues/2#issuecomment-280870001), even though it doesn't actually work on iOS 10.

**Comment by brymonster** [comment]
Ok. I have the iOS kern utils executables, but but can't figure out how to package as deb.  

-bryan

**Comment by Siguza** [comment]
Why do you need to package them as deb? Just put them on your device via ssh/scp/sftp, unzip and run.

**Comment by brymonster** [comment]
ok i assumed it would need to be packaged as a deb. 
i moved them into /Downloads. and uninstalled the previous 1.3.2 version. 
no need to install anything? just run the above commands?

**Comment by Siguza** [comment]
Yes, that should be all that is required.

**Comment by brymonster** [comment]
Ok. Well just placing the files doesn't make nvpatch executable. But I thank u m for all your help. 

-bryan

**Comment by brymonster** [comment]
i have tried the 1.3.2. kern utils deb, that seemed just to crash my device. but the experimental raw files i cant seem to get to run using `nvpatch com.apple.System.boot-nonce` seems like im missing how to unpack or run them.
i have also used nonceEnabler, and when checking with `nvram -p` it matches with the nonce generator (even after reboots)

`nvram -p`:
<img width="565" alt="screen shot 2017-02-27 at 8 46 49 pm" src="https://cloud.githubusercontent.com/assets/12586478/23392043/ec385b80-fd2d-11e6-9f38-c69d840e5313.png">

**generator:**
<img width="310" alt="screen shot 2017-02-27 at 8 40 04 pm" src="https://cloud.githubusercontent.com/assets/12586478/23391890/f6aae0b6-fd2c-11e6-9c39-5baa1dc72088.png">

but it seems the nonce isnt actually getting set since i get stuck waiting for the right nonce.
<img width="717" alt="waiting for nonce" src="https://cloud.githubusercontent.com/assets/12586478/23391910/176bcd56-fd2d-11e6-9ab4-74e39c36bc11.png">
any ideas?

**Comment by Siguza** [comment]
If you just unpacked the zip, you'd have to run the commands as `./nvpatch` from the current directory.

And it seems hardly possible that the NVRAM variable gets set, but not "really"... could you check whether, if you try this multiple times (set a generator, try futurerestore, repeat), the first nonce is always `7d 7d a0 ...`?

**Comment by brymonster** [comment]
whats weird is the strange response from `nvram -p` its alwas the same. even after reboot. (shouldnt it change?)
>iBad:/var/mobile/Downloads/ios-kern-utils root# nvram -p
backlight-level	1607
com.apple.System.fp-state	%00%00%00%00`%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00
boot-args	
auto-boot	true
com.apple.system.boot-nonce	0x16720224aed2294e

i finally got the nvpatch installed successfully tho. (sorry im learning) still the same.
[recent.txt](https://github.com/Siguza/cl0ver/files/809556/recent.txt)

since i set the generator this way i dont need to set the nonce? or i need to do both. 
reboot. cl0ver. nvpatch. set nonce. nonceEnabler? futurerestore...?

**Comment by Siguza** [comment]
Welp... I know very little about restores, you're probably better off asking tihmstar.

**Comment by ubiko** [comment]
@Siguza sorry for the delay, yes I have 2.3 but I think it's just my blobs that are invalid. Thanks for the help anyway :)

**Comment by erfanoabdi** [comment]
@brymonster hey did you find any fix for this issue we're on same boat 
i've patched cl0ver and nvpatch(also tested with nonce) and nvram sets but after reboot for recovery it's keeps restarting to find device AP :( 
__________________
iPhone 5s(GSM) 9.0.2

**Comment by Siguza** [comment]
@erfanoabdi You spelled the variable name wrong. It's `com.apple.System.boot-nonce` with a capital `S`.

**Comment by erfanoabdi** [comment]
@Siguza tnx for reply 
absolutely and here's the output :
```
iPhone:/var/mobile/Media/Downloads root# nvpatch com.apple.System.boot-nonce
[*] Successfully patched permissions for variable "com.apple.System.boot-nonce"
iPhone:/var/mobile/Media/Downloads root# nvram com.apple.System.boot-nonce=0x6fc9c699fcc8c04
iPhone:/var/mobile/Media/Downloads root# nvram -p
backlight-level	1531
boot-args	
com.apple.System.boot-nonce	0x6fc9c699fcc8c04
obliteration	handle_message: Obliteration Complete
auto-boot	true
oblit-begins	OblitType: ObliterateDataPartition. No reason given.
iPhone:/var/mobile/Media/Downloads root# reboot
Connection to 192.168.1.37 closed by remote host.
Connection to 192.168.1.37 closed.
Erfans-MacBook-Pro:futurerestore-latest erfanabdi$ ssh root@192.168.1.37
root@192.168.1.37's password: 
iPhone:~ root# nvram -p
backlight-level	1531
com.apple.System.boot-nonce	0x6fc9c699fcc8c04
boot-args	
obliteration	handle_message: Obliteration Complete
auto-boot	true
oblit-begins	OblitType: ObliterateDataPartition. No reason given.
```
but when i reboot to recovery and reboot to OS : 

```
iPhone:~ root# nvram -p
backlight-level	1531
boot-args	
obliteration	handle_message: Obliteration Complete
auto-boot	true
oblit-begins	OblitType: ObliterateDataPartition. No reason given.
```

also i removed all of JB tweaks using semirestore9

**Comment by Siguza** [comment]
I'm not sure how exactly the nonce is handled by iBoot, but as I understand it, it's cleared on a normal boot, so that should be expected behaviour. Question is, do you get different first nonces in Recovery Mode?

**Comment by erfanoabdi** [comment]
no every time it generates different nonces at first

**Comment by brymonster** [comment]
@erfanoabdi
Like Siguza said, capital S. 
I kept trying until the nvpatch would work. Then run futurerestore. But I never got it to work. Supposedly my blobs were invalid, but they didn't present a problem before. I have updated since. 10.3 :/ 
Sorry I'm no help.

**Comment by zeezooPL** [comment]
I've to an iPad Air 1, iOS 7.1.2 jailbroken with Pangu 1.2.1, so tfp0 should be enabled and I'm unable to set nonce. 

"root# nvpatch com.apple.System.boot-nonce
[!] Failed to locate kernel"

" root# ./nvrampatcher
[-] Failed to access the kernel task (error 0)."

" root# ./nonceEnabler
separt=com.apple.System.sep.art
[!] failed to get the kernel base address"

Any solutions? Maybe someone had similar issue on iOS 7.

Regards,
zeezoo
