### ISSUE TITLE
i cant do it...

### ISSUE THREAD

**Issue by kimmansur** [Siguza/cl0ver#38]
I tried to copy offsets but no sucess can you help me ?
iPhone 6s 9.0.2 Pangu Jailbreak.

**Comment by TwentyFour-24** [comment]
Hey there,

we need a little more information to help you properly.
How far did you get? Which offset file did you use? What commands did you enter? What's the error message?

**Comment by Siguza** [comment]
I'm closing this due to lack of response as well as information.

Feel free to open a new ticket, but please follow the [usage](https://github.com/Siguza/cl0ver#usage) guide in the readme, and describe your problem in a way that answers the following questions:
- What exactly are you doing?
- What are you expecting?
- What is happening instead?

**Comment by kimmansur** [comment]
Sorry about this lag! When i enter cydia returns an error about some folders that supposed to be there. I tryied to add those folders trought terminal, but at terminal it returns sandbox error.
